### ISSUE TITLE
[SHEL-105] User ID equal 0 in GET /products

### ISSUE THREAD

**Issue by wutpppppppppppppppppp** [Pelter-Team/Pelter-Backend#14]
Info and material are in bug ticket SHEL-105 [ticket](https://kwinyarut.atlassian.net/browse/SHEL-105?atlOrigin=eyJpIjoiYjQzMmI4Njg1NGM2NGQzOThmMDQxNTAyNTc2YzJlYTkiLCJwIjoiaiJ9)

**Comment by wit03** [comment]
fixed in #15
