### ISSUE TITLE
A change in product's entity.

### ISSUE THREAD

**Issue by wutpppppppppppppppppp** [Pelter-Team/Pelter-Backend#7]
Since I'm developing transaction api endpoint, I think there is a mistake in product entity. TransactionID shouldn't be there because, to create a product, there might not be a transaction yet. Moreover, I think it might be a good idea to add a product mock data in db for easier development. Or maybe any suggestion would be great! Thank you

**Comment by wit03** [comment]
Solved in #9 

Now current struct looks like this:
```go
type Product struct {
	ID             uint `gorm:"primary_key"`
	UserID         uint
	Review         []Review
	Name           string
	IsSold         bool
	Category       string
	Subcategory    string
	Description    string
	IsVerified     bool
	Price          float64
	ImageURL       string
	VaccineBookURL *string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
```
It does not contain both `TransactionID` and `Transaction` since the relation should be like this:
`Transaction -> Product`
not 
`Product -> Transaction`
